export const STORES = [
  {
    id: '1',
    code: 'S001',
    name: 'Sumirê Centro',
    region: 'São Paulo - Sul',
    status: 'Ativo',
    coverage: 85,
    manager: 'Carlos Silva',
    address: 'Rua Direita, 123 - Centro',
  },
  {
    id: '2',
    code: 'S002',
    name: 'Sumirê Paulista',
    region: 'São Paulo - Centro',
    status: 'Ativo',
    coverage: 100,
    manager: 'Ana Paula',
    address: 'Av. Paulista, 1000',
  },
  {
    id: '3',
    code: 'S003',
    name: 'Sumirê Guarulhos',
    region: 'Guarulhos',
    status: 'Inativo',
    coverage: 0,
    manager: 'Roberto Santos',
    address: 'Rua Dom Pedro, 45',
  },
  {
    id: '4',
    code: 'S004',
    name: 'Sumirê Campinas',
    region: 'Campinas',
    status: 'Ativo',
    coverage: 60,
    manager: 'Fernanda Lima',
    address: 'Av. Brasil, 800',
  },
  {
    id: '5',
    code: 'S005',
    name: 'Sumirê Osasco',
    region: 'Osasco',
    status: 'Ativo',
    coverage: 40,
    manager: 'Julio Cesar',
    address: 'Rua Antônio Agu, 300',
  },
]

export const PROMOTERS = [
  {
    id: '1',
    name: 'Mariana Alves',
    category: 'Cabelos',
    brands: ["L'Oréal", 'Pantene'],
    phone: '(11) 98765-4321',
    status: 'Em Rota',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=1',
  },
  {
    id: '2',
    name: 'João Mendes',
    category: 'Maquiagem',
    brands: ['Vult', 'Maybelline'],
    phone: '(11) 91234-5678',
    status: 'Check-in Ativo',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=2',
  },
  {
    id: '3',
    name: 'Beatriz Costa',
    category: 'Perfumaria',
    brands: ['Boticário', 'Natura'],
    phone: '(11) 99876-5432',
    status: 'Folga',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=3',
  },
  {
    id: '4',
    name: 'Lucas Pereira',
    category: 'Cabelos',
    brands: ['Embelleze', 'Seda'],
    phone: '(11) 95555-4444',
    status: 'Em Rota',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=4',
  },
]

export const VISITS = [
  {
    id: '1',
    promoterId: '2',
    promoterName: 'João Mendes',
    storeId: '2',
    storeName: 'Sumirê Paulista',
    time: '10:30',
    status: 'Em Andamento',
    type: 'Check-in',
  },
  {
    id: '2',
    promoterId: '1',
    promoterName: 'Mariana Alves',
    storeId: '1',
    storeName: 'Sumirê Centro',
    time: '09:15',
    status: 'Concluída',
    type: 'Visita',
  },
  {
    id: '3',
    promoterId: '4',
    promoterName: 'Lucas Pereira',
    storeId: '4',
    storeName: 'Sumirê Campinas',
    time: '08:00',
    status: 'Concluída',
    type: 'Visita',
  },
  {
    id: '4',
    promoterId: '1',
    promoterName: 'Mariana Alves',
    storeId: '5',
    storeName: 'Sumirê Osasco',
    time: '14:20',
    status: 'Agendada',
    type: 'Pendente',
  },
]

export const CATEGORIES = [
  { id: '1', name: 'Cabelos', items: 1240, activePromoters: 45 },
  { id: '2', name: 'Maquiagem', items: 850, activePromoters: 30 },
  { id: '3', name: 'Perfumaria', items: 420, activePromoters: 15 },
  { id: '4', name: 'Cuidados Pessoais', items: 600, activePromoters: 20 },
  { id: '5', name: 'Unhas', items: 300, activePromoters: 10 },
]

export const BRANDS = [
  { id: '1', name: "L'Oréal", category: 'Cabelos', status: 'Ativo' },
  { id: '2', name: 'Vult', category: 'Maquiagem', status: 'Ativo' },
  { id: '3', name: 'Embelleze', category: 'Cabelos', status: 'Ativo' },
  { id: '4', name: 'Maybelline', category: 'Maquiagem', status: 'Inativo' },
]
